import streamlit as st
import os
import sys

# Import from local streamlit_agent packages
from agents.architecture_logic import (
    check_handoff_status,
    execute_agent_stream,
    save_result,
    get_file_name_for_lens,
    SYSTEM_PROMPTS
)
from agents.graph_agent import run_document_refiner
from utils import get_docs_dir

# Smart path detection for local running directory
IS_DOCKER = os.path.exists("/app/documents")
base_docs_dir = "/app/documents" if IS_DOCKER else os.path.abspath(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "documents"))
assets_dir = os.path.join(base_docs_dir, "assets")

def render(selected_model, llm_engine, server_host):
    # Initialize active lens state
    if "active_lens" not in st.session_state:
        st.session_state.active_lens = "Summary Lens"
        
    # ---------------------------------------------------------------
    # Responsive Architecture Grid Map
    # ---------------------------------------------------------------
    st.markdown("<h4 style='text-align: center; color: #0284c7; margin-top: 1rem; margin-bottom: 1rem;'>🏗️ Technical Architecture Orchestrator Node Map</h4>", unsafe_allow_html=True)
    
    # CSS styling for the node containers
    st.markdown("""
    <style>
    .node-arrow {
        text-align: center;
        color: #0ea5e9;
        font-weight: bold;
        font-size: 1.5rem;
        line-height: 1;
        margin: 5px 0;
    }
    </style>
    """, unsafe_allow_html=True)
    
    # Grid of buttons
    r1_col1, r1_col2, r1_col3 = st.columns(3)
    
    # Spacing and vertical arrows row
    arrow_col1, arrow_col2, arrow_col3 = st.columns(3)
    
    # Central row
    r2_col1, r2_col2, r2_col3 = st.columns(3)
    
    # Spacing and vertical arrows row 2
    arrow2_col1, arrow2_col2, arrow2_col3 = st.columns(3)
    
    # Row 3
    r3_col1, r3_col2, r3_col3 = st.columns(3)
    
    def render_node(col, label, icon, lens_name):
        is_active = (st.session_state.active_lens == lens_name)
        btn_type = "primary" if is_active else "secondary"
        with col:
            if st.button(f"{icon} {label}", key=f"node_btn_{lens_name.lower().replace(' ', '_')}", use_container_width=True, type=btn_type):
                st.session_state.active_lens = lens_name
                st.rerun()

    # Row 1 (Top Lenses)
    render_node(r1_col1, "Business Lens", "💼", "Business Lens")
    render_node(r1_col2, "Application Lens", "📱", "Application Lens")
    render_node(r1_col3, "Infrastructure Lens", "☁️", "Infrastructure Lens")
    
    # Arrows Row 1
    with arrow_col1:
        st.markdown('<div class="node-arrow">↙</div>', unsafe_allow_html=True)
    with arrow_col2:
        st.markdown('<div class="node-arrow">⬇</div>', unsafe_allow_html=True)
    with arrow_col3:
        st.markdown('<div class="node-arrow">↘</div>', unsafe_allow_html=True)
        
    # Central Row
    with r2_col1:
        st.write("") # Empty placeholder to keep layout balanced
    render_node(r2_col2, "Summary Lens (Central Orchestrator)", "🏗️", "Summary Lens")
    with r2_col3:
        st.write("") # Empty placeholder
        
    # Arrows Row 2
    with arrow2_col1:
        st.markdown('<div class="node-arrow">↖</div>', unsafe_allow_html=True)
    with arrow2_col2:
        st.markdown('<div class="node-arrow">⬆</div>', unsafe_allow_html=True)
    with arrow2_col3:
        st.markdown('<div class="node-arrow">↗</div>', unsafe_allow_html=True)
        
    # Row 3 (Bottom Lenses & Document Hub)
    render_node(r3_col1, "Security Lens", "🔒", "Security Lens")
    render_node(r3_col2, "Data Lens", "💾", "Data Lens")
    render_node(r3_col3, "Document Node", "📁", "Document Node")

    active_lens = st.session_state.active_lens
    target_doc = get_file_name_for_lens(active_lens)
    
    st.markdown("---")
    
    # ---------------------------------------------------------------
    # Document Node View
    # ---------------------------------------------------------------
    if active_lens == "Document Node":
        st.markdown("### 📁 Architecture Document Hub")
        st.markdown("Manage and inspect all modular architecture documents generated by the subagents.")
        
        proj_dir = get_docs_dir()
        all_files = os.listdir(proj_dir)
        arch_files = [f for f in all_files if f.startswith("architecture_") and f.endswith(".md")]
        
        if not arch_files:
            st.info("No architectural documents found in this project. Go to the subagent lenses to generate them.")
        else:
            selected_file = st.selectbox("Select document to present/inspect:", sorted(arch_files))
            if selected_file:
                filepath = os.path.join(proj_dir, selected_file)
                try:
                    with open(filepath, "r", encoding="utf-8") as f:
                        file_content = f.read()
                        
                    with st.container(border=True):
                        st.markdown(f"#### 📄 File: `{selected_file}`")
                        st.markdown("---")
                        
                        edit_mode = st.toggle("✍️ Edit Document Manually", key=f"edit_mode_{selected_file}")
                        if edit_mode:
                            edited_text = st.text_area("Edit Content", value=file_content, height=450, key=f"ta_edit_{selected_file}")
                            if st.button("💾 Save Changes", key=f"btn_save_{selected_file}", use_container_width=True):
                                with open(filepath, "w", encoding="utf-8") as wf:
                                    wf.write(edited_text)
                                st.toast("✅ Document updated successfully!")
                                st.rerun()
                        else:
                            st.markdown(file_content)
                            
                        # Download button
                        st.download_button(
                            label="⬇️ Download Document",
                            data=file_content,
                            file_name=selected_file,
                            mime="text/markdown",
                            use_container_width=True
                        )
                except Exception as e:
                    st.error(f"Error loading document: {e}")
        return

    # ---------------------------------------------------------------
    # Subagent / Lens Workspace Layout (Split columns)
    # ---------------------------------------------------------------
    col_input, col_out = st.columns([1, 1.2])
    
    with col_input:
        # Load handoff status
        status_class, status_text = check_handoff_status()
        st.markdown(f"""
        <div class="handoff-status {status_class}">
            {status_text}
        </div>
        """, unsafe_allow_html=True)
        
        # Load current lens content from file if exists
        proj_dir = get_docs_dir()
        filepath = os.path.join(proj_dir, target_doc)
        current_content = ""
        if os.path.exists(filepath):
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    current_content = f.read()
            except Exception:
                pass
                
        # Main Subagent controls
        with st.container(border=True):
            st.markdown(f"### ⚙️ {active_lens} Subagent Configurations")
            
            tech_pref = st.text_input("Tech Stack Preferences", placeholder="e.g. Python (FastAPI), React, Postgres, Supabase...", key="arch_tech")
            scale = st.text_input("Expected Traffic / User Base", placeholder="e.g. 100 orders/day at launch, up to 10k users/month...", key="arch_scale")
            compliance = st.text_input("Compliance / Safety Needs", placeholder="e.g. Secure payments, Indian DPDP compliance...", key="arch_compliance")
            
            st.markdown("<br>", unsafe_allow_html=True)
            
            # Action Buttons
            btn_exec_label = f"✨ Execute {active_lens} Subagent"
            generate_lens_btn = st.button(btn_exec_label, key=f"btn_exec_{active_lens.lower().replace(' ', '_')}")
            
        # Display corresponding lens architecture diagram
        lens_image_map = {
            "Business Lens": "business_lens.png",
            "Application Lens": "application_lens.png",
            "Infrastructure Lens": "infrastructure_lens.png",
            "Security Lens": "security_lens.png",
            "Data Lens": "data_lens.png"
        }
        
        if active_lens in lens_image_map:
            img_file = lens_image_map[active_lens]
            local_img_path = os.path.join(assets_dir, img_file)
            if os.path.exists(local_img_path):
                st.image(local_img_path, caption=f"🏗️ {active_lens} Topology Diagram", use_column_width=True)
            else:
                st.info(f"💡 Visual diagram asset not found. Run generator or add to `documents/assets/{img_file}`.")
        else:
            st.markdown(f"""
            <div style="background-color: rgba(2, 132, 199, 0.05); padding: 1.25rem; border-radius: 12px; border: 1px solid rgba(2, 132, 199, 0.15);">
                <h5 style="color: #0284c7; margin-top:0;">🏗️ Central Orchestrator Summary</h5>
                <p style="font-size:0.88rem; color:#334155; line-height:1.5;">
                    The Summary Lens aggregates all other architecture branches (Business, Application, Infrastructure, Security, Data) 
                    into a cohesive executive strategy document. Navigate through nodes to generate/refine details.
                </p>
            </div>
            """, unsafe_allow_html=True)

        # ---------------------------------------------------------------
        # Floating Draggable Chat Popover for Active Lens Refinement
        # ---------------------------------------------------------------
        if current_content:
            st.markdown("""
            <style>
            /* Position the popover container as fixed on the bottom-left of screen */
            div[data-testid="stPopover"] {
                position: fixed !important;
                bottom: 30px !important;
                left: 30px !important;
                right: auto !important;
                top: auto !important;
                z-index: 999999 !important;
            }
            /* Style the button as a circular chat bubble */
            div[data-testid="stPopover"] button {
                border-radius: 50% !important;
                width: 65px !important;
                height: 65px !important;
                font-size: 30px !important;
                box-shadow: 0 8px 24px rgba(0,0,0,0.3) !important;
                background: linear-gradient(135deg, #0284c7 0%, #0369a1 100%) !important;
                color: white !important;
                border: none !important;
                display: flex !important;
                align-items: center !important;
                justify-content: center !important;
                transition: transform 0.2s ease-in-out !important;
                cursor: move !important;
            }
            div[data-testid="stPopover"] button:hover {
                transform: scale(1.1) !important;
                box-shadow: 0 10px 32px rgba(0,0,0,0.4) !important;
            }
            /* Hide the down arrow SVG icon inside the popover button */
            div[data-testid="stPopover"] button svg {
                display: none !important;
            }
            /* Adjust the floating popup window width/style */
            div[data-testid="stPopoverBody"] {
                width: 400px !important;
                max-width: 90vw !important;
                border-radius: 16px !important;
                box-shadow: 0 12px 40px rgba(0,0,0,0.25) !important;
                border: 1px solid rgba(0, 0, 0, 0.1) !important;
                background-color: #ffffff !important;
            }
            </style>
            """, unsafe_allow_html=True)
            

            with st.popover("💬"):
                st.markdown(f"<h3 style='margin-top:0;'>💬 Refine {active_lens}</h3>", unsafe_allow_html=True)
                
                chat_container = st.container(height=350)
                with chat_container:
                    chat_hist_key = f"chat_history_{target_doc.replace('.', '_')}"
                    if chat_hist_key not in st.session_state:
                        st.session_state[chat_hist_key] = []
                    for msg in st.session_state[chat_hist_key]:
                        with st.chat_message(msg["role"]):
                            st.markdown(msg["content"])
                
                chat_input = st.chat_input("Suggest changes or ask Q&A...", key=f"chat_in_{target_doc.replace('.', '_')}")
                if chat_input:
                    with st.chat_message("user"):
                        st.markdown(chat_input)
                    st.session_state[chat_hist_key].append({"role": "user", "content": chat_input})
                    
                    lens_system_prompt = f"You are the specialist subagent assisting with the {active_lens}.\n\n"
                    lens_system_prompt += f"System Persona & Guidelines:\n{SYSTEM_PROMPTS.get(active_lens)}\n\n"
                    lens_system_prompt += f"Your target document is '{target_doc}'. Use tools to read and write updates."
                    
                    with st.chat_message("assistant"):
                        response = run_document_refiner(
                            chat_history=st.session_state[chat_hist_key][:-1],
                            user_message=chat_input,
                            project_folder=st.session_state.get("current_project", "default_project"),
                            target_doc=target_doc,
                            agent_system_prompt=lens_system_prompt,
                            selected_model=selected_model,
                            llm_engine=llm_engine,
                            server_host=server_host
                        )
                    st.session_state[chat_hist_key].append({"role": "assistant", "content": response})
                    st.rerun()

    with col_out:
        if generate_lens_btn:
            if not st.session_state.shared_idea.strip():
                st.warning("⚠️ Please describe your Business Idea in the fields above first.")
            else:
                with st.container(border=True):
                    status_placeholder = st.empty()
                    status_placeholder.markdown(
                        f'<div class="agent-thinking">'
                        f'Subagent designing {active_lens}'
                        f'<span class="thinking-dot"></span>'
                        f'<span class="thinking-dot"></span>'
                        f'<span class="thinking-dot"></span>'
                        f'</div>',
                        unsafe_allow_html=True
                    )
                    output_placeholder = st.empty()
                    
                    full_text = ""
                    try:
                        stream = execute_agent_stream(
                            lens=active_lens,
                            shared_idea=st.session_state.shared_idea,
                            tech_pref=tech_pref,
                            scale=scale,
                            compliance=compliance,
                            selected_model=selected_model,
                            llm_engine=llm_engine,
                            server_host=server_host
                        )
                        for chunk in stream:
                            full_text += chunk
                            status_placeholder.empty()
                            output_placeholder.markdown(full_text)
                        
                        save_result(active_lens, full_text)
                        st.toast(f"✅ Automatically saved '{target_doc}' to Shared Memory!")
                        st.rerun()
                    except Exception as e:
                        status_placeholder.error(f"Error: {e}")
                        
        elif current_content:
            edit_mode = st.toggle("✍️ Edit Document Manually", key=f"edit_toggle_{target_doc.replace('.', '_')}")
            
            if edit_mode:
                edited_text = st.text_area("Edit Architecture Document", value=current_content, height=450, key=f"txt_area_edit_{target_doc.replace('.', '_')}")
                if st.button("💾 Save Changes", key=f"btn_save_man_{target_doc.replace('.', '_')}", use_container_width=True):
                    save_result(active_lens, edited_text)
                    st.toast("✅ Manual edits saved successfully!")
                    st.rerun()
            else:
                with st.container(border=True):
                    st.markdown(current_content)
                    
            col_dl, col_sav = st.columns([1, 1])
            with col_dl:
                st.download_button(
                    label="⬇️ Download Markdown",
                    data=current_content,
                    file_name=target_doc,
                    mime="text/markdown",
                    use_container_width=True,
                    key=f"dl_btn_{target_doc.replace('.', '_')}"
                )
            with col_sav:
                if st.button("💾 Save to Shared Memory", key=f"sav_btn_{target_doc.replace('.', '_')}", use_container_width=True):
                    save_result(active_lens, current_content)
                    st.toast(f"✅ Saved '{target_doc}' to Shared Memory!")
                    st.rerun()
        else:
            st.markdown(f"""
            <div class="empty-agent-state">
                <div class="icon">🏗️</div>
                <div class="title">{active_lens} Subagent</div>
                <div class="sub">Click "Execute {active_lens} Subagent" to analyze and design this specific lens.</div>
            </div>
            """, unsafe_allow_html=True)
