import os
from .common_utils import get_docs_dir, load_shared_memory, stream_chat

class SupervisorAgent:
    """
    The Supervisor Agent coordinates the multi-agent strategy pipeline.
    It validates handoff states, evaluates cross-document alignment/consistency,
    and acts as a centralized strategy orchestrator.
    """
    
    REQUIRED_DOCUMENTS = {
        "1_vision_mission": "vision_mission.md",
        "2_research": "market_research.md",
        "3_requirements": "prd_requirements.md",
        "4_planning": "launch_plan.md",
        "5_architecture": "technical_architecture.md"
    }

    @classmethod
    def get_pipeline_status(cls, project_folder: str = None) -> dict:
        """
        Scans the project directory and returns the completion status
        and handoff capability for each step in the pipeline.
        """
        # Save old env variable if needed, or use the active project
        if project_folder:
            old_project = os.environ.get("CURRENT_PROJECT")
            os.environ["CURRENT_PROJECT"] = project_folder
            
        proj_dir = get_docs_dir()
        
        status = {}
        # Base check for business idea
        idea_exists = os.path.exists(os.path.join(proj_dir, "business_idea.txt"))
        status["business_idea"] = {
            "exists": idea_exists,
            "filename": "business_idea.txt",
            "label": "💡 Business Idea"
        }
        
        # Check all agent documents
        for agent_key, filename in cls.REQUIRED_DOCUMENTS.items():
            path = os.path.join(proj_dir, filename)
            exists = os.path.exists(path)
            status[agent_key] = {
                "exists": exists,
                "filename": filename,
                "label": agent_key.replace("_", " ").title()
            }
            
        # Handoff recommendation logic
        # e.g., Step N requires Step N-1 to be complete
        status["1_vision_mission"]["ready_to_execute"] = idea_exists
        status["2_research"]["ready_to_execute"] = status["1_vision_mission"]["exists"]
        status["3_requirements"]["ready_to_execute"] = status["2_research"]["exists"]
        status["5_architecture"]["ready_to_execute"] = status["3_requirements"]["exists"]
        status["4_planning"]["ready_to_execute"] = status["5_architecture"]["exists"]
        
        if project_folder and 'old_project' in locals() and old_project:
            os.environ["CURRENT_PROJECT"] = old_project
            
        return status

    @classmethod
    def run_consistency_audit(cls, selected_model: str, llm_engine: str, server_host: str, project_folder: str = None):
        """
        Reads all strategy documents in the project and performs an audit,
        pointing out misalignments, contradictions, or gaps.
        """
        if project_folder:
            old_project = os.environ.get("CURRENT_PROJECT")
            os.environ["CURRENT_PROJECT"] = project_folder
            
        proj_dir = get_docs_dir()
        
        # Load all documents
        docs_content = {}
        for agent_key, filename in cls.REQUIRED_DOCUMENTS.items():
            path = os.path.join(proj_dir, filename)
            if os.path.exists(path):
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        docs_content[filename] = f.read()
                except Exception as e:
                    docs_content[filename] = f"[Error reading file: {e}]"
                    
        # Check if business idea exists
        idea_path = os.path.join(proj_dir, "business_idea.txt")
        idea_text = ""
        if os.path.exists(idea_path):
            with open(idea_path, "r", encoding="utf-8") as f:
                idea_text = f.read()
                
        if not docs_content:
            yield "❌ No strategy documents found in Shared Memory. Please run the agents first to generate content for audit."
            return
            
        # Compile auditing system prompt
        audit_prompt = f"""You are the Master AI Strategy Supervisor. Your task is to perform a rigorous consistency and alignment audit across all generated business files for the project.
Here is the core Business Idea:
{idea_text}

Here are the strategy documents generated by individual agents:
"""
        for filename, content in docs_content.items():
            audit_prompt += f"\n--- DOCUMENT: {filename} ---\n{content}\n"
            
        audit_prompt += """
Please analyze all documents and output a detailed audit report:
1. **🔍 Executive Alignment Check**: Does each document align with the core business idea?
2. **⚠️ Contradictions or Mismatches**: Identify any direct contradictions. For example:
   - Does the Technical Architecture recommend a stack that conflicts with the constraints set in the Launch Plan or Requirements?
   - Do the MVP features in the Requirements document conflict with the scope analyzed in the Market Research?
   - Is there a discrepancy in target audience or region between Vision & Mission and Market Research?
3. **💡 Strategic Gaps**: Are there crucial details left out in one document that were assumed in another?
4. **🛠️ Actionable Recommendations**: Suggest specific updates to resolve any issues. Keep the suggestions practical and modular.
"""
        
        messages = [
            {"role": "system", "content": "You are a professional, sharp-witted AI strategy coordinator and auditor. Be concise but thorough."},
            {"role": "user", "content": audit_prompt}
        ]
        
        try:
            for chunk in stream_chat(messages, selected_model, llm_engine, server_host):
                yield chunk
        except Exception as e:
            yield f"Error running audit: {e}"
            
        if project_folder and 'old_project' in locals() and old_project:
            os.environ["CURRENT_PROJECT"] = old_project
